
package uk.co.listpoint.contextmap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContextMap6ServiceSoap", targetNamespace = "http://www.listpoint.co.uk/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContextMap6ServiceSoap {


    /**
     * Download the contents of a ContextMap as an XML document
     * 
     * @param contextMapName
     * @param targetEDTName
     * @param userName
     * @param sourceEDTName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMap6Structure
     */
    @WebMethod(operationName = "Download", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/Download")
    @WebResult(name = "ContextMap", targetNamespace = "http://www.listpoint.co.uk/schemas/v6")
    @RequestWrapper(localName = "Download", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.Download")
    @ResponseWrapper(localName = "ContextMap", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMap")
    public ContextMap6Structure download(
        @WebParam(name = "ContextMapName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String contextMapName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "SourceEDTName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String sourceEDTName,
        @WebParam(name = "TargetEDTName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String targetEDTName,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Get the status of a ContextMap
     * 
     * @param userName
     * @param existingContextMapName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMapStatusResponse6Type
     */
    @WebMethod(operationName = "Status", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/Status")
    @WebResult(name = "ContextMapStatusResponse", targetNamespace = "http://www.listpoint.co.uk/messages/ContextMap")
    @RequestWrapper(localName = "Status", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.Status")
    @ResponseWrapper(localName = "ContextMapStatusResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMapStatusResponse")
    public ContextMapStatusResponse6Type status(
        @WebParam(name = "ExistingContextMapName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String existingContextMapName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Start a new draft of an existing ContextMap
     * 
     * @param userName
     * @param existingContextMapName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMapStartNewDraftResponse6Type
     */
    @WebMethod(operationName = "StartNewDraft", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/StartNewDraft")
    @WebResult(name = "ContextMapStartNewDraftResponse", targetNamespace = "http://www.listpoint.co.uk/messages/ContextMap")
    @RequestWrapper(localName = "StartNewDraft", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.StartNewDraft")
    @ResponseWrapper(localName = "ContextMapStartNewDraftResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMapStartNewDraftResponse")
    public ContextMapStartNewDraftResponse6Type startNewDraft(
        @WebParam(name = "ExistingContextMapName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String existingContextMapName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Delete an existing draft ContextMap
     * 
     * @param draftContextMapName
     * @param userName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMapDeleteDraftResponse6Type
     */
    @WebMethod(operationName = "DeleteDraft", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/DeleteDraft")
    @WebResult(name = "ContextMapDeleteResponse", targetNamespace = "http://www.listpoint.co.uk/messages/ContextMap")
    @RequestWrapper(localName = "DeleteDraft", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.DeleteDraft")
    @ResponseWrapper(localName = "ContextMapDeleteResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMapDeleteResponse")
    public ContextMapDeleteDraftResponse6Type deleteDraft(
        @WebParam(name = "DraftContextMapName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String draftContextMapName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Find all draft ContextMaps based on an existing published ContextMap
     * 
     * @param publishedContextMapName
     * @param userName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMapFindDraftsResponse6Type
     */
    @WebMethod(operationName = "FindDrafts", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/FindDrafts")
    @WebResult(name = "ContextMapFindDraftsResponse", targetNamespace = "http://www.listpoint.co.uk/messages/ContextMap")
    @RequestWrapper(localName = "FindDrafts", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.FindDrafts")
    @ResponseWrapper(localName = "ContextMapFindDraftsResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMapFindDraftsResponse")
    public ContextMapFindDraftsResponse6Type findDrafts(
        @WebParam(name = "PublishedContextMapName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String publishedContextMapName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Upload an XML document to replace the contents of an existing draft ContextMap
     * 
     * @param request
     * @return
     *     returns uk.co.listpoint.contextmap.ContextMapUploadResponse6Type
     */
    @WebMethod(operationName = "Upload", action = "http://www.listpoint.co.uk/soapAction/v6-1/ContextMap/Upload")
    @WebResult(name = "ContextMapUploadResponse", targetNamespace = "http://www.listpoint.co.uk/messages/ContextMap")
    @RequestWrapper(localName = "Upload", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.Upload")
    @ResponseWrapper(localName = "ContextMapUploadResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.contextmap.ContextMapUploadResponse")
    public ContextMapUploadResponse6Type upload(
        @WebParam(name = "request", targetNamespace = "http://www.listpoint.co.uk/webservices")
        ContextMapUploadRequest6Type request);

}
