
package uk.co.listpoint.context;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A service to allow Contexts to be maintained automatically under program control
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Context6Service", targetNamespace = "http://www.listpoint.co.uk/webservices", wsdlLocation = "META-INF/wsdl/Context6Service.wsdl")
public class Context6Service
    extends Service
{

    private final static URL CONTEXT6SERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTEXT6SERVICE_EXCEPTION;
    private final static QName CONTEXT6SERVICE_QNAME = new QName("http://www.listpoint.co.uk/webservices", "Context6Service");

    static {
        CONTEXT6SERVICE_WSDL_LOCATION = uk.co.listpoint.context.Context6Service.class.getClassLoader().getResource("META-INF/wsdl/Context6Service.wsdl");
        WebServiceException e = null;
        if (CONTEXT6SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/Context6Service.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONTEXT6SERVICE_EXCEPTION = e;
    }

    public Context6Service() {
        super(__getWsdlLocation(), CONTEXT6SERVICE_QNAME);
    }

    public Context6Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTEXT6SERVICE_QNAME, features);
    }

    public Context6Service(URL wsdlLocation) {
        super(wsdlLocation, CONTEXT6SERVICE_QNAME);
    }

    public Context6Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTEXT6SERVICE_QNAME, features);
    }

    public Context6Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Context6Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Context6ServiceSoap
     */
    @WebEndpoint(name = "Context6ServiceSoap")
    public Context6ServiceSoap getContext6ServiceSoap() {
        return super.getPort(new QName("http://www.listpoint.co.uk/webservices", "Context6ServiceSoap"), Context6ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Context6ServiceSoap
     */
    @WebEndpoint(name = "Context6ServiceSoap")
    public Context6ServiceSoap getContext6ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.listpoint.co.uk/webservices", "Context6ServiceSoap"), Context6ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTEXT6SERVICE_EXCEPTION!= null) {
            throw CONTEXT6SERVICE_EXCEPTION;
        }
        return CONTEXT6SERVICE_WSDL_LOCATION;
    }

}
