
package uk.co.listpoint.context;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Context6ServiceSoap", targetNamespace = "http://www.listpoint.co.uk/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Context6ServiceSoap {


    /**
     * Download the contents of a Context as an XML document
     * 
     * @param edtName
     * @param userName
     * @param password
     * @param contextName
     * @param version
     * @return
     *     returns uk.co.listpoint.context.Context6Structure
     */
    @WebMethod(operationName = "Download", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/Download")
    @WebResult(name = "Context", targetNamespace = "http://www.listpoint.co.uk/schemas/v6")
    @RequestWrapper(localName = "Download", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.Download")
    @ResponseWrapper(localName = "Context", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.Context")
    public Context6Structure download(
        @WebParam(name = "ContextName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String contextName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "EDTName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String edtName,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Get the status of a Context
     * 
     * @param userName
     * @param existingContextName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.context.ContextStatusResponse6Type
     */
    @WebMethod(operationName = "Status", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/Status")
    @WebResult(name = "ContextStatusResponse", targetNamespace = "http://www.listpoint.co.uk/messages/Context")
    @RequestWrapper(localName = "Status", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.Status")
    @ResponseWrapper(localName = "ContextStatusResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.ContextStatusResponse")
    public ContextStatusResponse6Type status(
        @WebParam(name = "ExistingContextName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String existingContextName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Start a new draft of an existing Context
     * 
     * @param userName
     * @param existingContextName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.context.ContextStartNewDraftResponse6Type
     */
    @WebMethod(operationName = "StartNewDraft", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/StartNewDraft")
    @WebResult(name = "ContextStartNewDraftResponse", targetNamespace = "http://www.listpoint.co.uk/messages/Context")
    @RequestWrapper(localName = "StartNewDraft", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.StartNewDraft")
    @ResponseWrapper(localName = "ContextStartNewDraftResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.ContextStartNewDraftResponse")
    public ContextStartNewDraftResponse6Type startNewDraft(
        @WebParam(name = "ExistingContextName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String existingContextName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Delete an existing draft Context
     * 
     * @param draftContextName
     * @param userName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.context.ContextDeleteDraftResponse6Type
     */
    @WebMethod(operationName = "DeleteDraft", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/DeleteDraft")
    @WebResult(name = "ContextDeleteResponse", targetNamespace = "http://www.listpoint.co.uk/messages/Context")
    @RequestWrapper(localName = "DeleteDraft", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.DeleteDraft")
    @ResponseWrapper(localName = "ContextDeleteResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.ContextDeleteResponse")
    public ContextDeleteDraftResponse6Type deleteDraft(
        @WebParam(name = "DraftContextName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String draftContextName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Find all draft Contexts based on an existing published Context
     * 
     * @param publishedContextName
     * @param userName
     * @param password
     * @param version
     * @return
     *     returns uk.co.listpoint.context.ContextFindDraftsResponse6Type
     */
    @WebMethod(operationName = "FindDrafts", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/FindDrafts")
    @WebResult(name = "ContextFindDraftsResponse", targetNamespace = "http://www.listpoint.co.uk/messages/Context")
    @RequestWrapper(localName = "FindDrafts", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.FindDrafts")
    @ResponseWrapper(localName = "ContextFindDraftsResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.ContextFindDraftsResponse")
    public ContextFindDraftsResponse6Type findDrafts(
        @WebParam(name = "PublishedContextName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String publishedContextName,
        @WebParam(name = "version", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String version,
        @WebParam(name = "UserName", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://www.listpoint.co.uk/webservices")
        String password);

    /**
     * Upload an XML document to replace the contents of an existing draft Context
     * 
     * @param request
     * @return
     *     returns uk.co.listpoint.context.ContextUploadResponse6Type
     */
    @WebMethod(operationName = "Upload", action = "http://www.listpoint.co.uk/soapAction/v6-1/Context/Upload")
    @WebResult(name = "ContextUploadResponse", targetNamespace = "http://www.listpoint.co.uk/messages/Context")
    @RequestWrapper(localName = "Upload", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.Upload")
    @ResponseWrapper(localName = "ContextUploadResponse", targetNamespace = "http://www.listpoint.co.uk/webservices", className = "uk.co.listpoint.context.ContextUploadResponse")
    public ContextUploadResponse6Type upload(
        @WebParam(name = "request", targetNamespace = "http://www.listpoint.co.uk/webservices")
        ContextUploadRequest6Type request);

}
