
package uk.co.listpoint.codelist;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A service to allow Code Lists to be maintained automatically under program control
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CodeList6Service", targetNamespace = "http://www.listpoint.co.uk/webservices", wsdlLocation = "META-INF/wsdl/CodeList6Service.wsdl")
public class CodeList6Service
    extends Service
{

    private final static URL CODELIST6SERVICE_WSDL_LOCATION;
    private final static WebServiceException CODELIST6SERVICE_EXCEPTION;
    private final static QName CODELIST6SERVICE_QNAME = new QName("http://www.listpoint.co.uk/webservices", "CodeList6Service");

    static {
        CODELIST6SERVICE_WSDL_LOCATION = uk.co.listpoint.codelist.CodeList6Service.class.getClassLoader().getResource("META-INF/wsdl/CodeList6Service.wsdl");
        WebServiceException e = null;
        if (CODELIST6SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CodeList6Service.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CODELIST6SERVICE_EXCEPTION = e;
    }

    public CodeList6Service() {
        super(__getWsdlLocation(), CODELIST6SERVICE_QNAME);
    }

    public CodeList6Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CODELIST6SERVICE_QNAME, features);
    }

    public CodeList6Service(URL wsdlLocation) {
        super(wsdlLocation, CODELIST6SERVICE_QNAME);
    }

    public CodeList6Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CODELIST6SERVICE_QNAME, features);
    }

    public CodeList6Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CodeList6Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CodeList6ServiceSoap
     */
    @WebEndpoint(name = "CodeList6ServiceSoap")
    public CodeList6ServiceSoap getCodeList6ServiceSoap() {
        return super.getPort(new QName("http://www.listpoint.co.uk/webservices", "CodeList6ServiceSoap"), CodeList6ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CodeList6ServiceSoap
     */
    @WebEndpoint(name = "CodeList6ServiceSoap")
    public CodeList6ServiceSoap getCodeList6ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.listpoint.co.uk/webservices", "CodeList6ServiceSoap"), CodeList6ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CODELIST6SERVICE_EXCEPTION!= null) {
            throw CODELIST6SERVICE_EXCEPTION;
        }
        return CODELIST6SERVICE_WSDL_LOCATION;
    }

}
